---
#CLACore plugin for PocketMine-MP

#@Author: CLADevs Team


#----------------------------------------# JOIN #----------------------------------------#
#Teleport you to spawn when you join & login
#true or false
Alway-Spawn: true

#----------------------------------------# RANK #----------------------------------------#
#Allow Rank in their chat and above head
#true or false
Allow-Rank: true

#----------------------------------------# MONEY SYSTEM #---------------------------------#
#allow you to use a personalized economy of money
#true or false
Allow-Money: true

#----------------------------------------# TITLE #----------------------------------------#
#You can edit title, subtitle in title.yml

#Allow big text in screen when you respawn
#true or false
Title-Respawn: true

#Allow big text in screen when you join
#true or false
Title-Join: true
...
