---
#CLACore plugin for PocketMine-MP

#@Author: CLADevs Team

#----------------------------------------# JOIN #----------------------------------------#
#Teleport you to spawn when you join & login
#true or false
Always-Spawn: true

#----------------------------------------# RANK #----------------------------------------#
#Allow Rank in their chat and above head
#true or false
Allow-Rank: true

#----------------------------------------# MONEY SYSTEM #---------------------------------#
#allow you to use a personalized economy of money
#true or false
Allow-Money: true

#----------------------------------------# TITLE #----------------------------------------#
#You can edit title, subtitle in title.yml

#Allow big text in screen when you respawn
#true or false
Title-Respawn: true

#Allow big text in screen when you join
#true or false
Title-Join: true

#Disable Hunger Changing
#So players can always sprint :D
Disable-HungerChange: true

#----------------------------------------# NO VOID #----------------------------------------#
#You can edit this here for allow no void on world
#Allow no void on world empty
Allow-NoVoid: true
#Name world to allow the no void system
No-Void-World: "hub"

#---------------------------------------# HIGHPING KICK #-----------------------------------#
#Enable or Disable this option if you want that players with high ping get kicked
Enable-HighPingKick: true
Max-Ping: 500
...
